### ISSUE TITLE
Imagery within .integrations-block on homepage not showing up in Firefox & Edge

### ISSUE THREAD

**Issue by jendowns** [cushion/cushionapp.com#1]
Hello there! 👋

I love your website -- the design is absolutely delightful! 

I noticed a layout issue in Firefox (v 52.0) and Edge (v 14) that I just wanted to bring to your attention...

At the bottom of the homepage in the "Integrate Your Existing Tools" section, none of the images (or image containers) show up, so the whole left side of that section is blank in Firefox and Edge. It looks like each `.integrations-block__image-item` elem has a `height: 0;` and then each child `.integrations-block__image-container` is set to `position: absolute;`. So neither of those element types are participating in the layout, so to speak. And since no other children have heights set, the parent(s) collapse.

Thanks for taking a look at this! 😄

**Comment by destroytoday** [comment]
![bert-stare-o](https://cloud.githubusercontent.com/assets/158963/24049162/9180108e-0b01-11e7-8118-5b68cb15bcc5.gif)

Thanks for letting me know about this, Jen! I admit, we sometimes forget to check Firefox. 😬 I'll be sure to fix it.
